<?php $pageTitle='Platform Features'; include 'includes/header.php';
$sections=[
'Student Site'=>['Landing & authentication','College email/OTP verification','Google OAuth integration point','Manual verification fallback','Student profile and dashboard','Trust Score and history','Skills with levels 1–5','Verified/unverified skill badges','Timed/randomized assessments','Integrity monitoring hooks','Assessment history and review request','GitHub/coding-profile integration points','Certificate/external proofs','Project portfolio and peer review','Job discovery and applications','Hackathon team discovery','Screening tasks','Messaging and notifications'],
'Recruiter Site'=>['Recruiter/company registration & verification','Recruiter dashboard','Company profile','Create/edit/close job listings','Candidate discovery and filters','Verified-only and Trust Score filters','Candidate profiles','Save/shortlist workflow','Opportunity outreach','Screening tasks and submissions','Recruiter-candidate messaging','Premium/export integration points'],
'Team Leader Site'=>['Team-leader authentication','Team dashboard','Create hackathon team','Roles and skills required','Team members and skill matrix','Skill-gap analysis','Candidate discovery','Verified-only search','Invitation and join-request workflow','Screening tasks','Verification logs','Communication and notifications','Candidate comparison and analytics foundations'],
'Common Backend'=>['Centralized authentication','Role-based access control','Assessment engine tables','Trust Score engine/logs','Matching data model','Verification records','Proctoring/integrity data model','Notification service data','Messaging service','External integration data','Users/skills/assessments/projects/teams/jobs/applications tables','Admin user management','Manual verification','Assessment/document/report review','Skill/hackathon/job management','Account suspension']]; ?>
<div class="kicker">Implementation map</div><h1>Unimesh Feature Coverage</h1><p class="muted">This PHP/MySQL starter implements the core flows directly and leaves external services such as Google OAuth, email OTP delivery, GitHub APIs, webcam AI, secure code execution and PDF/CSV generation as integration points that require provider credentials or separate services.</p>
<?php foreach($sections as $name=>$items):?><div class="card section-title"><h2><?=e($name)?></h2><ul class="feature-list"><?php foreach($items as $i):?><li>✓ <?=e($i)?></li><?php endforeach;?></ul></div><?php endforeach;?>
<?php include 'includes/footer.php'; ?>
